### ISSUE TITLE
Broken Endpoints March 26

### ISSUE THREAD

**Issue by srmor** [NJIT-CLASS/backend#13]
Ok so I did another sweep through the endpoints. Here are the broken ones. Please please test your endpoints... I really don't have time to debug your endpoints every week :crying_cat_face:.
- [x] `GET` `/generalUser/:userid`
- [x] `PUT` `/update/email`
- [x] `POST` `/CreateSemester`
- [x] `GET` `/semester/:semesterid`
- [x] `GET` `/semester`
- [x] `POST` `/course/create`
- [x] `POST` `/course/createsection`
- [x] `PUT` `/course/adduser`
- [x] `GET` `/course/:courseId`
- [x] `PUT` `/course/updatesection`
- [x] `GET` `/course/getCourses/:userid`
- [x] `POST` `/resetPassword`
- [x] `POST` `/resetUserPassword`

I made comments in the code with the errors I was getting.

**Comment by cesarl88** [comment]
Can you post the error? I don't see them.

**Comment by srmor** [comment]
If you go to notifications: https://github.com/notifications they should be there, but if you just hit the endpoints you will get them as well.

**Comment by cesarl88** [comment]
All the following test were done using the database in the test server (Not in local database)
- GET /generalUser/:userid
  {"Error":false,"Message":"Success","User":      [{"FirstName":"Christian","LastName":"Alexander","UserType":null,"Email":"cga4@njit.edu"}]}
- PUT /update/email
  Fixed
  {
  "Error": false,
  "Message": "Success",
  "EmailAddress": "cesarl_88@hotmail.com"
  }
-  POST /CreateSemester
  404 Error returned when start Date is greater than EndDate
  404 Error returned when Dates are not sent with the request
  Request with no name:
  {
  "SemesterID": 3
  }
  Request with Name:
  {
  "SemesterID": 4
  }
-  GET /semester/:semesterid
  Fixed
  Response:
  {
  "Error": false,
  "Message": "Success",
  "Course": [
    {
      "SemesterID": 1,
      "Name": "Test Semester",
      "StartDate": "2016-01-01T05:00:00.000Z",
      "EndDate": "2016-05-01T04:00:00.000Z"
    }
  ]
  }
- GET /semester
  Fixed
  {
  "Error": false,
  "Message": "Success",
  "Semesters": [
    {
      "SemesterID": 1,
      "Name": "Test Semester",
      "StartDate": "2016-01-01T05:00:00.000Z",
      "EndDate": "2016-05-01T04:00:00.000Z",
      "OrganizationID": 1
    },
    {
      "SemesterID": 2,
      "Name": "Test Semester 2",
      "StartDate": "1994-10-09T04:00:00.000Z",
      "EndDate": "1995-12-09T05:00:00.000Z",
      "OrganizationID": 1
    },
    {
      "SemesterID": 3,
      "Name": null,
      "StartDate": "2016-05-20T04:00:00.000Z",
      "EndDate": "2016-05-30T04:00:00.000Z",
      "OrganizationID": null
    },
    {
      "SemesterID": 4,
      "Name": "Test",
      "StartDate": "2016-05-20T04:00:00.000Z",
      "EndDate": "2016-05-30T04:00:00.000Z",
      "OrganizationID": null
    }
  ]
  }
-  POST /course/create
  Fixed
  {
  "result": [
    {
      "LAST_INSERT_ID()": 4
    }
  ]
  }
-  GET /course/:courseId 
  Fixed
  Test: courseid = 2
  {
  "Error": false,
  "Message": "Success",
  "Course": [
    {
      "Number": "CS-113",
      "Title": "Computer Science A"
    }
  ]
  }
  Test: courseid = 1
  {
  "Error": false,
  "Message": "Success",
  "Course": [
    {
      "Number": "CS-100",
      "Title": "Intro to Computer Science"
    }
  ]
  }
-  PUT /course/adduser
  Fixed
  Test userid = 1
  {
  "Error": false,
  "Message": "Success",
  "UserID": 3
  }
- PUT /course/updatesection
  Fixed and validation for mandatory fields has been added
-  GET /course/getCourses/:userid
  Fixed
  {
  "Error": false,
  "Message": "Success",
  "Result": [
    {
      "CourseID": 2,
      "SectionID": 2
    },
    {
      "CourseID": 1,
      "SectionID": 3
    }
  ]
  }
  UserID = 2
  {
  "Error": false,
  "Message": "Success",
  "Result": [
    {
      "CourseID": 2,
      "SectionID": 2
    }
  ]
  }
-  POST /course/createsection
  Fixed
  {
  "result": [
    {
      "LAST_INSERT_ID()": 6
    }
  ]
  }

The last two issues are pending because the stored procedures have not been created yet due to some permission issues.

Please let me know if you have any issue with these end points again.

**Comment by cesarl88** [comment]
Reset Password has been implemented but we just need to finish the email notification

**Comment by srmor** [comment]
`PUT` `/update/email` changes the user's password in the `Login` table, but it does not change their email in the `UserContact` table making their be inconsistencies between `/generalUser` and `/login`

**Comment by srmor** [comment]
If at all possible @cesarl88 could this bug be fixed before the midterm? ^

**Comment by cga101** [comment]
If Cesar doesn't get to it tonight, I shall.

Gonna play catch-up tonight.

On Sun, Apr 3, 2016 at 12:31 AM, Stephen Morrison notifications@github.com
wrote:

> If at all possible @cesarl88 https://github.com/cesarl88 could this bug
> be fixed before the midterm? ^
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/NJIT-CLASS/backend/issues/13#issuecomment-204865121

## 

_Christian Alexander_
NJIT - _Albert Dorman Honors College *- Class of 2016
Major : *Computer Science_
Debate League -
_President_
ACM - _Student Tutor_

**Comment by cesarl88** [comment]
@srmor I have fixed the issue with the update email but you have pushed the sequelize module to the repository and I had to pull it and fix so many conflicts manually before I could do any push. All the modules have reference to my local environment.

Please test and make sure everything is working properly.

**Comment by srmor** [comment]
Thanks @cesarl88! Sorry about that. I just pushed because I needed the module to be added to be able to run it on the test server properly.

**Comment by srmor** [comment]
@cesarl88 just fixed a couple things that got messed up with the merge conflicts (all the environment variables). Looks like your fix is working great. Thanks!
